### PR TITLE
Supermicro X8 raw PSU stats added

### PR DESCRIPTION
**Pull request by teran**
In X8 MB's there're some metrics not present in sensors
view, so added them as a raw commands.

PS. It's highly recommended to test that code against Supermicro MB's other than X8 before merging.

### CODE REVIEW

**Comment by teran** [comment]
Update: tested on HP server: works fine with output as 0
Please let me know if you think that's acceptable result or it's better to hide it from output.

**Review by SqiSch — APPROVED** [review]

**Comment by SqiSch** [comment]
@teran Can you please merge the newest master to your branch to resolve the conflicts. Thx for your PR.

**Comment by teran** [comment]
@SqiSch done.

**Comment by teran** [comment]
Update: cleaned up the staff about merge-commit, so now it's clean and linear against your HEAD

**Comment by SqiSch** [comment]
Thank you.

**Pull request merged**
